---
- name: 'variables - ensure validated'
  tags: 'gitannex'
  assert:
    that:
      - '{{ item.result }}'
    quiet: '{{ gitannex__checks_quiet }}'
  loop:
    - result: '{{ gitannex__repositories_manage is boolean }}'
      desc: 'gitannex__repositories_manage is boolean'
      value: '{{ gitannex__repositories_manage }}'
    - result: '{{ gitannex__repositories_state in ["present", "absent"] }}'
      desc: 'gitannex__repositories_state in ["present", "absent"]'
      value: '{{ gitannex__repositories_state }}'
    - result: '{{ gitannex__repositories_enabled is boolean }}'
      desc: 'gitannex__repositories_enabled is boolean'
      value: '{{ gitannex__repositories_enabled }}'
    - result: '{{ gitannex__packages_manage is boolean }}'
      desc: 'gitannex__packages_manage is boolean'
      value: '{{ gitannex__packages_manage }}'
    - result: '{{ gitannex__packages_state in ["present", "absent"] }}'
      desc: 'gitannex__packages_state in ["present", "absent"]'
      value: '{{ gitannex__packages_state }}'
  loop_control:
    label: '{{ item.desc }}'
