---
- name: 'include OS family specific variables'
  tags: 'gitannex'
  include_vars: '{{ ansible_os_family }}.yml'

- import_tasks: 'validate.yml'
  tags: 'gitannex'

- import_tasks: 'repositories.yml'
  when: gitannex__repositories_manage
  tags: 'gitannex'

- import_tasks: 'packages.yml'
  when: gitannex__packages_manage
  tags: 'gitannex'
